"""
Django settings for KeyMaster project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import dj_database_url
import environ

environ.Env()
environ.Env.read_env()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&s8_p8gnk+3v&pt)3)51w#&mf@e!gf7&n*jqoo!f23*m7s&r*w"

###########################################################################################
# When ready, delete lines 29-30 and uncomment out lines 34-36. You may need to edit default="".
# SECRET_KEY = os.environ.get(
#     "SECRET_KEY", default="django-insecure-&s8_p8gnk+3v&pt)3)51w#&mf@e!gf7&n*jqoo!f23*m7s&r*w"
# )
###########################################################################################

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

###########################################################################################
# When ready, delete line 40 and uncomment out line 44.
# DEBUG = "RENDER" not in os.environ
###########################################################################################

ALLOWED_HOSTS = []

###########################################################################################
# When ready, uncomment out lines 51-53
# RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
# if RENDER_EXTERNAL_HOSTNAME:
#     ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
###########################################################################################

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main_app",
    "widget_tweaks",
    ###########################################################################################
    # When ready, uncomment out line 69
    # "corsheaders",
    ###########################################################################################
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    ##########################################################################################
    # When ready, uncomment out line 77
    # "whitenoise.middleware.WhiteNoiseMiddleware",
    ###########################################################################################
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    ##########################################################################################
    # When ready, uncomment out line 83
    # "corsheaders.middleware.CorsMiddleware",
    ###########################################################################################
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "KeyMaster.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "KeyMaster.wsgi.application"

##########################################################################################
# When ready, uncomment out line 114
# CORS Settings
# CORS_ORIGIN_ALLOW_ALL = True
###########################################################################################

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Local Host
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "keymaster",
    }
}

##########################################################################################
# When ready, uncomment out lines 131-136
# Render
# DATABASES = {
#     "default": dj_database_url.config(
#         conn_max_age=600,
#         conn_health_checks=True,
#     )
# }
##########################################################################################

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "main_app/static/")]

##########################################################################################
# When ready, uncomment out lines 178-180
# if not DEBUG:
#     STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
#     STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
##########################################################################################

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "/records/"
LOGOUT_REDIRECT_URL = "/"
