# Generated by Django 4.2.3 on 2023-07-13 23:51

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_record_options_alter_record_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': [django.db.models.functions.text.Upper('website')]},
        ),
    ]
